# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 01:26
from __future__ import unicode_literals
from hashlib import sha256

from django.db import migrations
from django.utils.text import slugify


def deduplicate_slugs(apps, _):
    Restaurant = apps.get_model('core', 'Restaurant')

    for r in Restaurant.objects.all():
        hash = sha256('{}-{}'.format(r.name, r.id).encode('utf8')).hexdigest()[:10]
        r.slug = slugify('{} {}'.format(r.name, hash))
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190505_2253'),
    ]

    operations = [
        migrations.RunPython(deduplicate_slugs),
    ]
