# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190505_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avatar',
            field=models.URLField(default='bla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='bla', max_length=255),
            preserve_default=False,
        ),
    ]
