# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190507_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
