# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190507_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ifood_url',
            field=models.URLField(default='fake url'),
            preserve_default=False,
        ),
    ]
