# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 17:00
from __future__ import unicode_literals
from csv import DictReader

from django.db import migrations
from django.utils.text import slugify


def get_models(apps, model_names, app_name='core'):
    return [apps.get_model(app_name, model) for model in model_names]


def eager_load_data(csv_name):
    with open(csv_name) as f:
        return [item for item in DictReader(f)]


def load_restaurants(apps, _):
    Restaurant, Cuisine, PriceRange = get_models(apps, [
        'Restaurant',
        'Cuisine',
        'PriceRange'
    ])

    restaurant_data = eager_load_data('data/restaurants.csv')

    for r in restaurant_data:
        price_range, _ = PriceRange.objects.get_or_create(name=r['price_range'])
        cuisine, _ = Cuisine.objects.get_or_create(name=r['category'])
        restaurant = Restaurant(
            name=r['name'],
            delivery_fee=r['delivery_fee'],
            rating=r['rating'],
            avatar=r['avatar'],
            slug=slugify(r['name']),
            price_range=price_range,
            cuisine=cuisine
        )

        restaurant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190505_1657'),
    ]

    operations = [
        migrations.RunPython(load_restaurants),
    ]
