# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 04:57
from __future__ import unicode_literals
from csv import DictReader

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def eager_load_data(csv_name):
    with open(csv_name) as f:
        return [item for item in DictReader(f)]


def load_ifood_url(apps, _):
    restaurant_data = eager_load_data('data/restaurants.csv')
    Restaurant = apps.get_model('core', 'Restaurant')

    for item in restaurant_data:
        try:
            r = Restaurant.objects.get(avatar=item['avatar'], name=item['name'])
            r.ifood_url = item['url']
            r.save()
        except ObjectDoesNotExist:
            print('Restaurant "{}" not in database. Skipping.'.format(item['name']))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_restaurant_ifood_url'),
    ]

    operations = [
        migrations.RunPython(load_ifood_url),
    ]
