# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190505_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='preference',
            name='rejected_cuisines',
            field=models.ManyToManyField(related_name='rejected_by', to='core.Cuisine'),
        ),
        migrations.AddField(
            model_name='preference',
            name='selected_cuisines',
            field=models.ManyToManyField(related_name='selected_by', to='core.Cuisine'),
        ),
    ]
