# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190505_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='id',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='type',
        ),
        migrations.AddField(
            model_name='preference',
            name='max_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='only_free_delivery',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preference',
            name='price_range',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='core.PriceRange'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
