# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190505_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='max_rating',
            new_name='min_rating',
        ),
    ]
